devices:
  - "npu"
backend_extension: "torch_npu"
link: https://github.com/Ascend/pytorch
models:
  - model: yolov3
    skip: true

  - model: yolov3
    skip: true
batch_size: 1
extra_args:
  - "--accuracy"
