name: "Install artifact with pip"
description: "Install artifact with pip"
inputs:
  artifact:
    description: "The distribution artifact name"
    type: string
    required: true

# TODO: https://github.com/actions/runner/issues/3620
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}

    - name: Install artifact
      shell: bash
      run: |
        pip install ${{ inputs.artifact }}
