name: '_ascend_npu_benchmark'

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        description: 'The runner selected to run on'
      image:
        required: true
        type: string
        description: 'The docker image which will be loaded'
      device:
        required: true
        type: string
        description: 'The device selected to run on'
      torch-artifact:
        required: true
        type: string
        description: 'The distribution artifact name of torch'
      torch-npu-artifact:
        required: true
        type: string
        description: 'The distribution artifact name of torch_npu'
    secrets:
      pr-token:
        description: 'A token used to create a pull request'
        required: true

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    name: run benchmarks for torch_npu
    runs-on: ${{ inputs.runner }}
    env:
      HF_ENDPOINT: https://hf-mirror.com
    container:
      image: ${{ inputs.image }}
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /etc/ascend_install.info:/etc/ascend_install.info
      options: >-
        --network host
        --device ${{ inputs.device }}
        --device /dev/davinci_manager
        --device /dev/devmm_svm
        --device /dev/hisi_hdc
      env:
        HTTP_PROXY: http://127.0.0.1:10809
        HTTPS_PROXY: http://127.0.0.1:10809
        ALL_PROXY: socks5://127.0.0.1:10808
        SOCKS_PROXY: socks5://127.0.0.1:10808
    steps:
      - name: Show NPU info
        run: |
          npu-smi info

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
              git gcc g++ make cmake ninja-build curl \
              libgl1 libglib2.0-0 libsndfile1

      # See: https://github.com/actions/checkout/issues/363#issuecomment-1915075699
      - name: Config git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout benchmark
        uses: actions/checkout@v4
        with:
          repository: pytorch/benchmark
          path: benchmark

      # TODO
      #- name: Install torch
      #  id: install-torch
      #  uses: ./.github/actions/install-torch
      #  with:
      #    torch-artifact: ${{ inputs.torch-artifact }}

      - name: Download torch artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.torch-artifact }}

      - name: Install torch
        shell: bash
        run: |
          pip install ${{ inputs.torch-artifact }}

      - name: List torch version
        id: install-torch
        shell: bash
        run: |
          torch_version=$(python -c "import torch; print(torch.__version__)")
          echo "torch-version=${torch_version}" >> $GITHUB_OUTPUT

      # We must use numpy 1.x
      - name: Generate pip's constraint file
        working-directory: ascend_npu
        run: |
          cat > constraint.txt << EOF
          torch==${{ steps.install-torch.outputs.torch-version }}
          numpy==1.*
          EOF

      - name: Download ${{ inputs.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ascend_npu

      - name: Install torch_npu
        working-directory: ascend_npu
        run: |
          pip install ${{ inputs.artifact_name }}

      #- name: Install torch_npu dependencies
      #  working-directory: ascend_npu
      #  run: |
      #    curl -fsSL -O https://raw.githubusercontent.com/Ascend/pytorch/refs/heads/master/requirements.txt
      #    pip install -r requirements.txt

      - name: Install benchmark dependencies
        run: |
          pip install -r benchmark/requirements.txt --constraint ascend_npu/constraint.txt
          python benchmark/install.py --userbenchmark test_bench --continue_on_fail

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Show environment info
        run: |
          npu_is_available=$(python -c "import torch; print(torch.npu.is_available())")
          npu_count=$(python -c "import torch; print(torch.npu.device_count())")
          echo "NPU is available: ${npu_is_available}"
          echo "NPU count: ${npu_count}"
          pip list | grep -E 'torch|numpy'

      - name: Run benchmarks
        working-directory: benchmark
        run: |
          python run_benchmark.py test_bench --accuracy --device npu --test eval \
              --output ascend_npu_benchmark.json

      - name: Upload the output file
        id: upload-output
        uses: actions/upload-artifact@v4
        with:
          name: ascend_npu_benchmark.json
          path: benchmark/ascend_npu_benchmark.json
          if-no-files-found: error
          retention-days: 1
          overwrite: true

      - name: Write to workflow job summary
        run: |
          python .ci/benchmark.py --write-gh-job-summary --path benchmark/ascend_npu_benchmark.json

      - name: Update README.md
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        id: update-readme
        run: |
          python .ci/benchmark.py --update-readme --path benchmark/ascend_npu_benchmark.json
          if git diff --quiet README.md; then
            echo "README.md not changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "README.md changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # See: https://github.com/peter-evans/create-pull-request
      - name: Create a pull request for changes to README.md
        if: ${{ steps.update-readme.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.pr-token }}
          base: ${{ github.head_ref }}
          committer: 'cosdt-bot <cosdtbot@gmail.com>'
          author: 'cosdt-bot <cosdtbot@gmail.com>'
          commit-message: 'Update torchbenchmark report in README.md'
          add-paths: README.md
          branch: ascend-npu/benchmark
          title: '[Ascend NPU] Update torchbenchmark report in README.md'
          body: |
            The torchbenchmark results running on Ascend NPU have changed, I'm updating the report in README.md.

            cc: @Yikun @hipudding @FFFrog @Zhenbin-8 @zeshengzong @wjunLu @MengqingCao @shink
          reviewers: shink
