name: '_ascend_npu_benchmark'

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        description: 'The runner selected to run on'
      image:
        required: true
        type: string
        description: 'The docker image which will be loaded'
      device:
        required: true
        type: string
        description: 'The device selected to run on'
      artifact_name:
        required: true
        type: string
        description: 'The torch_npu distribution artifact name'

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    name: run benchmarks for torch_npu
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.image }}
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /etc/ascend_install.info:/etc/ascend_install.info
      options: >-
        --network host
        --device ${{ inputs.device }}
        --device /dev/davinci_manager
        --device /dev/devmm_svm
        --device /dev/hisi_hdc
      env:
        HTTP_PROXY: http://127.0.0.1:10809
        HTTPS_PROXY: http://127.0.0.1:10809
        ALL_PROXY: socks5://127.0.0.1:10808
        SOCKS_PROXY: socks5://127.0.0.1:10808
    steps:
      - name: Show NPU info
        run: |
          npu-smi info

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install system dependencies
        run: |
          apt update
          apt install --no-install-recommends -y \
              git gcc g++ make cmake ninja-build curl \
              libgl1 libglib2.0-0 libsndfile1

      - name: Checkout
        uses: actions/checkout@v4

      # TODO(shink): Update once PR merged
      # https://github.com/pytorch/benchmark/pull/2550
      - name: Checkout benchmark
        uses: actions/checkout@v4
        with:
          repository: shink/benchmark
          ref: feat/test_bench/continue_on_error
          path: benchmark

      - name: Download ${{ inputs.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ascend_npu

      - name: Install torch_npu
        working-directory: ascend_npu
        run: |
          pip install ${{ inputs.artifact_name }}

      - name: Install torch_npu dependencies
        working-directory: ascend_npu
        run: |
          curl -fsSL -O https://raw.githubusercontent.com/Ascend/pytorch/refs/heads/master/requirements.txt
          pip install -r requirements.txt

      - name: Install benchmark dependencies
        run: |
          pip install -r benchmark/requirements.txt --constraint ascend_npu/requirements.txt "numpy==1.*"
          python benchmark/install.py --userbenchmark test_bench --continue_on_fail
        env:
          HF_ENDPOINT: https://hf-mirror.com

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Show environment info
        run: |
          npu_is_available=$(python -c "import torch; print(torch.npu.is_available())")
          npu_count=$(python -c "import torch; print(torch.npu.device_count())")
          echo "NPU is available: ${npu_is_available}"
          echo "NPU count: ${npu_count}"
          pip list | grep -E 'torch|numpy'

      - name: Run benchmarks
        working-directory: benchmark
        run: |
          python run_benchmark.py test_bench --accuracy --device npu --test eval --skip llava \
              --output ascend_npu_benchmark.json

      - name: Upload the output file
        id: upload-output
        uses: actions/upload-artifact@v4
        with:
          name: ascend_npu_benchmark.json
          path: benchmark/ascend_npu_benchmark.json
          if-no-files-found: error
          retention-days: 1
          overwrite: true

      - name: Write to workflow job summary
        run: |
          python .ci/benchmark.py --write-gh-job-summary --path benchmark/ascend_npu_benchmark.json

      - name: Update README.md
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        id: update-readme
        run: |
          python .ci/benchmark.py --update-readme --path benchmark/ascend_npu_benchmark.json
          if git diff --quiet README.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create a pull request for changes to README.md
        if: ${{ steps.update-readme.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: README.md
          branch: ascend-npu/benchmark
          title: "[Ascend NPU] Update torchbenchmark report in README.md"
          commit-message: "Update README.md"
          reviewers: shink
