name: '[Internal] Fetch and Rebase'

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        description: The runner selected to run on
      loop:
        required: true
        type: string
        description: Loop time when fails

jobs:
  fetch-and-rebase:
    runs-on: ${{ inputs.runner }}
    steps:
      #- name: Pull latest codes for torch
      #  uses: cosdt/pytorch-integration-tests/.github/actions/fetch-and-rebase@main
      #  with:
      #    repo_path: /home/runner/actions-runner/codes/pytorch/pytorch
      #    remote_branch: upstream/main
      #    loop: ${{ inputs.loop }}
      - name: Pull latest codes for torch_npu
        uses: ./.github/actions/fetch-and-rebase
        with:
          repo_path: /home/runner/actions-runner/codes/npu/pytorch
          remote_branch: upstream/master
          loop: ${{ inputs.loop }}
