# Note:
# Same runner only needs one job named like .*fetch-and-rebase

name: Ascend NPU Test Suite

on:
  push:
    branches:
      - 'main'
    paths:
      - '!**/*.md'

  pull_request:
    branches:
      - 'main'
    paths:
      - '!**/*.md'

  release:
    types:
      - 'published'

  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - self-hosted
        default: 'self-hosted'
        description: The runner selected to run on
      device:
        required: true
        type: choice
        options:
          - /dev/davinci1
          - /dev/davinci2
          - /dev/davinci3
          - /dev/davinci4
          - /dev/davinci5
          - /dev/davinci6
          - /dev/davinci7
          - /dev/davinci8
        default: '/dev/davinci6'
        description: 'The device selected to run on'
      image:
        required: true
        type: string
        default: 'ascendai/cann:7.1-openeuler2203sp2'
        description: The docker image which will be loaded

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-param.outputs.runner }}
      device: ${{ steps.set-param.outputs.device }}
      image: ${{ steps.set-param.outputs.image }}
    steps:
      - name: Set param
        id: set-param
        run: |
          set -e
          echo "runner=${{ github.event.inputs.runner || 'self-hosted' }}" >> $GITHUB_OUTPUT
          echo "device=${{ github.event.inputs.device || '/dev/davinci6' }}" >> $GITHUB_OUTPUT
          echo "image=${{ github.event.inputs.image || 'ascendai/cann:7.1-openeuler2203sp2' }}" >> $GITHUB_OUTPUT

  linux-py3_8-fetch-and-rebase:
    name: linux-py3_8-7.0.RC1.alpha005
    needs:
      - prepare
    uses: ./.github/workflows/_fetch_and_rebase.yml
    with:
      runner: ${{ needs.prepare.outputs.runner }}
      loop: 10

  linux-py3_8-build-and-test:
    name: linux-py3_8-7.0.RC1.alpha005
    needs:
      - prepare
      - linux-py3_8-fetch-and-rebase
    uses: ./.github/workflows/_build-and-test.yml
    with:
      runner: ${{ needs.prepare.outputs.runner }}
      device: ${{ needs.prepare.outputs.device }}
      image: ${{ needs.prepare.outputs.image }}
