name: Handle events from PyTorch

on:
  repository_dispatch:
    types: [pytorch-pr-event]

jobs:
  redispatch-pr-event:
    name: Redispatch PyTorch event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print PR event payload
        run: |
          echo "owner: ${{ github.event.client_payload.owner }}"
          echo "repo: ${{ github.event.client_payload.repo }}"
          echo "event_name: ${{ github.event.client_payload.event_name }}"
          echo "pull_request: ${{ toJson(github.event.client_payload.pull_request) }}"

      - name: Redispatch PyTorch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.COSDT_BOT_TOKEN }}
          repository: ${{ github.repository }}
          event-type: pytorch-pr-event-redispatch
          client-payload: ${{ toJson(github.event.client_payload) }}
