name: Receive event from PyTorch

on:
  repository_dispatch:
    types: [pytorch_event]

jobs:
  process-pr-event:
    name: Process PR event from PyTorch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Process PR event
        run: |
          echo "owner: ${{ github.event.client_payload.owner }}"
          echo "repo: ${{ github.event.client_payload.repo }}"
          echo "pull_request: ${{ github.event.client_payload.pull_request }}"
